### ISSUE TITLE
Installation Quide

### ISSUE THREAD

**Issue by Gator28** [Luluno01/BungeeGuard#1]
Hey, could you write up a short installation and configuration guide for me to follow? I don't have coding background so I'm a bit confused

**Comment by Luluno01** [comment]
The installation and configuration how-to should be quite clearly stated in [README](https://github.com/Luluno01/BungeeGuard/blob/master/README.md) for common server owners. However, worry not, I will tell you some more details.

First of all, considering that you are confused, I am not sure if you fully understand that this plugin is **NOT** a defense against UUID spoofing in offline mode. So here is the case, if you are running BungeeCord in offline mode and have no idea what is UUID/username spoofing and therefore have no offline authentication plugin installed, then you should first try figuring out what is UUID spoofing and why whitelist is not a defense againt that. Once you have understood, you will need to decide if you are still going to use a whitelist plugin because offline authentication plugin seems to do a better job.

If you are in online mode, congratulations, you are good to go. This plugin is a standard BungeeCord plugin. Therefore the installation should be the same as other BungeeCord plugins. In case you don't know how to install a BungeeCord plugin, you should follow the steps (quite similar to those of Bukkit/Spigot plugins):

1. Download the plugin (for this plugin, go to the release page or Spigot page), and what you will be downloading is a `.jar` file
2. Go to the directory where you put your `BungeeCord.jar` (or any other name for BungeeCord `.jar` file)
3. Create a `plugins` directory if it does not exist
4. Copy the plugin file you have just downloaded inside the `plugins` directory
5. Restart you BungeeCord server so that BungeeCord will find the new plugin in `plugins` directory and load it automatically on its start up

The only configuration of this plugin that you would probably like to manually modify is the messages to be delivered to blocked players, namely the `whitelist-message` and `blacklist-message` options in `config.yml`. Note that everytime you modify the `config.yml` file directly, you will need to reload the configuration by executing the command `bungeeguard reload` to push your changes to the plugin. Okay, once again, if you don't know how to do that, follow the steps if you want to **change messages to be delivered to blocked players**:

1. Install the plugin and start your BungeeCord server
2. Go to the `plugins` directory
3. Go inside the `BungeeGuard` directory
4. Edit the `config.yml` file, change the strings after `whitelist-message: ` and `blacklist-message: ` as you like and save your changes (note that you should keep the colon and the space, i.e. `: `)
5. Reload the configuration by going to the console of BungeeCord server, type `bungeeguard reload` and press enter. You are expected to see the feedback.

As for the other parts of the configuration, there is no need to modify them directly. You should use the commands as explained in [README](https://github.com/Luluno01/BungeeGuard/blob/master/README.md).

**Comment by Gator28** [comment]
Thank you so much for the reply, this really cleared a lot of things up!

**Comment by Luluno01** [comment]
NP ;P
