### ISSUE TITLE
Feature Request: API / Database Storage

### ISSUE THREAD

**Issue by NathanAdhitya** [Luluno01/BungeeGuard#11]
Hello, I've used BungeeSafeguard for a while and I'm looking for ways to programmatically whitelist/blacklist certain players. Making a plugin to execute console commands just for that purpose isn't really practical, eh?

Looking forward to seeing storage based on MySQL/MariaDB, MongoDB, or Redis, as well as a way to programmatically add new players to the whitelist/blacklist. Perhaps a REST API?

**Comment by Luluno01** [comment]
Introducing database or exposing non-JVM API will definitely bloat this plugin. That said, the features your are requesting are very normal in any production level applications. I would love to add these features but it requires me to potentially abandon currently refactored, not-yet-fully-tested code base, and start another major refactoring.

I decided to postpone this assignment until I have enough time and other resources to 1) test the first already refactored version, and then 2) go through the second refactoring with regard to your request. Before then, I would suggest you to write your own management plugin (not necessarily exclusive for controlling the whitelist/blacklist), which invokes the Java APIs currently exposed by BungeeSafeguard - you can get the plugin instance of BungeeSafeguard via BungeeCord API. Unfortunately, me myself don't have any experience in making an standalone API/SDK package so that another plugin can easily interact with my plugin. You are welcomed to submit PRs if you know how to do this ;)

**Comment by Luluno01** [comment]
Hi hi, initial refactoring and testing have been done but I am encountering problems in implementing a PoC plugin that interacts with BungeeSafeguard. The reason is the inability of sharing Kotlin runtime. Would you like to give it a try and see if you can come up with a solution? The unannounced release is available [here](https://github.com/Luluno01/BungeeSafeguard/releases/tag/v3.0).

**Comment by Luluno01** [comment]
Please check out the new 3.1 version and its extension plugins.
