### ISSUE TITLE
Error 403 when whitelist a Bedrock user

### ISSUE THREAD

**Issue by jAvEE-fr** [Luluno01/BungeeGuard#12]
hello i have issue whitelisting a player. can you add something like 
-> Add the code below in between uc.connect(); and uc.getInputStream();:

uc = url.openConnection();
uc.addRequestProperty("User-Agent", 
"Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0)");

(i see this fix in stackoverflow) to push an useragent to the xuid website.

thank you

**Comment by Luluno01** [comment]
Hi, which xbl-api are you using? I tested [this endpoint](https://xbl-api.prouser123.me) and it does not require a user agent value to access. Are you sure your issue is caused by missing user agent? Is there any chance that the gamer tag does not exist? If the cause can be confirmed, I will add proper user agent to the outgoing requests in next release (which might take a little longer).

**Comment by jAvEE-fr** [comment]
In error message there is url. When i click URL on my firefox on my pc there is XUID.

So it can be useragent error. My dedicated serveur have got a huge firewall... Maybe it is this?

Le 19 juin 2021 à 13:38, à 13:38, Untitled ***@***.***> a écrit:

**Comment by Luluno01** [comment]
I think I know what's happening. [This endpoint](https://xbl-api.prouser123.me/) is proxied by Cloudflare. Your server's network is probably rate limited or blocked by Cloudflare as suspicious attack source. Wait for a few more hours (or possibly days) and this issue may gone. If this happens frequently, consider deploy your own instance of [xbl-api](https://github.com/Prouser123/xbl-web-api).

**Comment by jAvEE-fr** [comment]
I'll try that thank you very much

Le 19 juin 2021 à 14:52, à 14:52, Untitled ***@***.***> a écrit:

**Comment by Luluno01** [comment]
NP :P

Just remember to update your config to instruct BungeeSafeguard to use your own API deployment.
