### ISSUE TITLE
Add Geyser/Floodgate whitelisting support for for Bedrock players

### ISSUE THREAD

**Issue by Frogperson** [Luluno01/BungeeGuard#5]
While using [Geyser](https://geysermc.org/) and [Floodgate](https://github.com/GeyserMC/Geyser/wiki/Floodgate) to allow Bedrock players to join a Java server, the only way to add them to the whitelist is by converting their XUID to a UUID by using a website such as this https://floodgate-uuid.heathmitchell1.repl.co/ and then manually editing this UUID into the config file for BungeeSafeguard and then reloading.

It would be really nice if this plugin could do all of that conversion automatically, maybe with a new `/whitelist bedrock-add DummyPlayer0 DummyPlayer1 00000000-0000-0000-0009-01f5856fe0de DummyPlayer2` command, or something similar.

If the automatic XUID conversion for Bedrock usernames isn't something you would want to add, then at least supporting the UUIDs in the normal whitelist command would be nice.

**Comment by Luluno01** [comment]
I guess it is possible. I need some time to figure out what it is :P

**Comment by Luluno01** [comment]
BTW, I think it is already possible to add UUID directly from the command. If it does not work, please tell me.

**Comment by Luluno01** [comment]
Hi, unfortunately I can't find any official or even third party XUID look up service which provides API access without the need of API key. If know any, please tell me.

## Short Answer

**Maybe I can't do this at the moment. But I can possibly try to write you a tailored script.**

## Long Answer

Yes, there are third party services but they only provide services to living human. Whereas `xapi.us` requires an API key - I can't just distribute my API key to all of you. What's more, after thinking it twice, I found it does not quite worth it for the following reasons:

### First Case

If we have to use `xapi.us`,

1. The user has to
  1. Register an `xapi.us` account
  2. Manage to grab the API key from `xapi.us`
  3. Put that key into BungeeSafeguard's config
2. I, the developer, have to
  1. Add a config entry for the API key
  2. Add a new command
  3. Add functionalities for calling `xapi.us` API
  4. Even more exception handling

Both parts sound simple, but the first part, i.e., the user side, is neither elegant nor easy for novice users to follow. Most importantly, third party username-to-XUID services are not reliable, they can be shut down at anytime.

### Second Case

If we allow users to specify both 1) which external username-to-XUID interface to use, 2)  credential to the designated interface, the system will bloat because I will have to implement a subsystem that supports as many API styles as possible. In that case it will be a heavy workload and kind of overkill.

### Third Case

If we will be building our own API service like [the one you are using](https://floodgate-uuid.heathmitchell1.repl.co/), I will have to

1. Be ready for API abuse
2. Buy a server
3. Buy a domain
4. Develop the server

Obviously, it is, again, kind of overkill.

### Fourth Case

If you got any great idea, please tell me.

**Comment by Frogperson** [comment]
Thanks for looking into this for me!

> BTW, I think it is already possible to add UUID directly from the command. If it does not work, please tell me.

To be honest I didn't test this myself, but I heard from somebody else that entering a UUID worked for Java players and not for Bedrock. I'm not able to test this right now so I can't verify if this is true or not.

I think there are other alternatives for getting an XUID other than xapi.us. For example this looks like it works pretty well https://github.com/Prouser123/xbl-web-api and returns an XUID without needing any API keys https://xbl-api.prouser123.me/xuid/Frogperson. I'm sure there are others out there as well, and I'd be happy to do some more research if this one doesn't work out.

Once you have the XUID in this format `xxxxxxxxxxxxxxxx` it should be simple to throw some `0`s and `-` in there to form a valid UUIUD like this `00000000-0000-0000-xxxx-xxxxxxxxxxxx`

**Comment by Luluno01** [comment]
Thanks, you have found a great open source XBOX API project. It works well as expected. So here is the plan, I will add a config that allow the users to specify the URL of deployed API, either their own deployment or the [default one](https://xbl-api.prouser123.me/). What do you think?

Besides, if someone is doing exactly what you are currently doing and find entering a UUID does not work for Bedrock, there could be something else unexpected happening there. I have tested the "entering a UUID converted from XUID" part, it worked. However, I don't have a proper XBOX account and Geyser setup for further testing. If what you are currently doing works for you, i.e., non-whitelisted players cannot get in while whitelisted players can, then it should probably be fine.

**Comment by Luluno01** [comment]
Could you please do a little bit testing for me because I currently have no way to test it. Thanks.

[BungeeSafeguard.main.zip](https://github.com/Luluno01/BungeeSafeguard/files/5255475/BungeeSafeguard.main.zip) (rename the extension name to `.jar`)

Oh you should add a new config entry `xbl-web-api: https://xbl-api.prouser123.me`.

---

If you are willing to do some testing for me, please do remember to test as many cases as possible, including some intended invalid input. If this is too troublesome for you, please at least check **the functionalities you are going use**. Very much obliged to you.

**Comment by Luluno01** [comment]
I found I do have an account for playing Bedrock edition for some reason. The tests seem well so I published it :P
