### ISSUE TITLE
Request: multiple whitelists support

### ISSUE THREAD

**Issue by MilesPernicious** [Luluno01/BungeeGuard#6]
Hello!

I currently have a few separate whitelists:

- admins only
- testers only
- normal whitelist

Currently I need to manage these on the filesystem by having 3 different copies of `config.yml`, and copying the one I want over existing one and then performing `/bungeesafeguard reload`

It would make my life easier if I could grant permission to admins to do this without needing filesystem access using a command such as
`/bungeesafeguard load <whitelist|blacklist> <listname>`

It may also be useful to have a configuration option to request confirmation before adding to a whiltelist with `/whitelist add` when multiple lists are used (for example, to prevent accidentally adding to the admins only whitelist)

**Comment by Luluno01** [comment]
I don't quite understand why you want to switch between multiple lists on the same network. Could you please take a few scenarios  as examples to help explain the situation?

**Comment by MilesPernicious** [comment]
For maintenance mode (configuring plugins, command blocks, creative building, etc) I would like to have only my admins on the network.

For certain things such as survival updates (from 1.16.1 to 1.16.3), or testing other experimental changes such as new plugins, command blocks, etc, I would like to only have those who are opted in for testing allowed on the network.

**Comment by Luluno01** [comment]
Kind of weird case... But I am working on it. It should be available in the next release.

**Comment by MilesPernicious** [comment]
If you don't wish to add it, I understand, because BungeeSafeguard is such a nice and elegant plugin that does its job well.  A little more background on what I am looking for is something similar to this, but with multiple whitelist support instead of only one.

https://www.spigotmc.org/resources/maintenance-bungee-and-spigot-support-1-8-1-16.40699/

**Comment by Luluno01** [comment]
Thank you and, yeah, I want to keep it as simple as possible such that it won’t be non-maintainable. Secondly, to be honest, switching between multiple configs does not seem to be a feature that would benefit the majority, or at least a small group of users. Anyway, I am working on it since it requires little extra effort and has relatively small impact on the code structure.

So what I am implementing now consists of two parts. The first one is config switching and the second is confirmation. Specifically, it is config switching but not list switching because the existence of lazy lists might make it a little ambiguous.

**Comment by Luluno01** [comment]
Hi, both features are implemented and now available in [v2.4](https://github.com/Luluno01/BungeeSafeguard/releases/tag/v2.4).
